### ISSUE TITLE
Fujifilm RAF files are not recognized

### ISSUE THREAD

**Issue by WaCaHe** [ktgw0316/LightZone#298]
I do not see anything about .RAF files from an XT-3 not being supported in the software. I am using the Beta 5.0.0-beta1

**Comment by FabulousSoldier** [comment]
Same here. I can view the .RAF files in Lighzone 5.0.0-beta1 but can't edit them. 
When trying to edit a .RAF file I get "Unsupported Camera".

Tried it with .RAF files from a GFX 50R and X100v.

**Comment by sfink16** [comment]
> I do not see anything about .RAF files from an XT-3 not being supported in the software. I am using the Beta 5.0.0-beta1

As seen in the release notes of [LZ 5.0.0-beta1](https://github.com/ktgw0316/LightZone/releases), [#270](https://github.com/ktgw0316/LightZone/issues/270) will eventually update all the missing cameras that DCRaw did not update.  As the release notes says this beta release will only "Show thumbnail/preview" for CR3 and apparently other cameras as well.   LZ had always used DCRaw to process images but it hasn't been update since 2018, leaving all newer cameras out.  LibRaw will be the replacement for newer cameras.

**Comment by ktgw0316** [comment]
Sorry for the inconvenience, I'll release [a fix](https://github.com/ktgw0316/LightZone/commit/6cde7872a0a095b4a33b3ea68e663578b7aff747#diff-a320b19bf4973479be53a4b608b2ae7d832e529094c539c5843e26aaf4c015b6R935) for this issue in 5.0.0beta2.

**Comment by WaCaHe** [comment]
> Sorry for the inconvenience, I'll release [a fix](https://github.com/ktgw0316/LightZone/commit/6cde7872a0a095b4a33b3ea68e663578b7aff747#diff-a320b19bf4973479be53a4b608b2ae7d832e529094c539c5843e26aaf4c015b6R935) for this issue in 5.0.0beta2.

I am not seeing any of the cameras we listed in your link. Per [#270](https://github.com/ktgw0316/LightZone/issues/270) linked above it looks like DCRaw doesn't support these cameras? If so that's a bummer.

**Comment by ktgw0316** [comment]
> I am not seeing any of the cameras we listed in your link.

Whoops... DCRaw doesn't support them, but LibRaw does. https://www.libraw.org/supported-cameras
